replicaCount: 1

image:
  repository: 192.168.90.53/pinbot/pinbot-exaone
  tag: "1.2b"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-secret

nameOverride: ""
fullnameOverride: "pinbot-exaone"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false

# ✅ GPU 노드 2개 공통 라벨 기준
nodeSelector:
  nvidia.com/gpu.present: "true"

# ❗ 아직 GPU 리소스 안 붙임 (중요)
resources: {}

container:
  port: 8000
  env:
    - name: ENV
      value: "dev"

