replicaCount: 1

nameOverride: "pinbot-exaone"
fullnameOverride: "pinbot-exaone"

image:
  repository: 192.168.90.53/pinbot/pinbot-exaone
  tag: "1.2b"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-secret

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

nodeSelector:
  gpu: "true"

nfs:
  server: 192.168.90.51
  path: /srv/pinbot/weights

resources:
  limits:
    nvidia.com/gpu: 1

shm:
  sizeLimit: 8Gi

env:
  - name: ENV
    value: dev

ingress:
  enabled: false
