replicaCount: 1

nameOverride: "pinbot-exaone"
fullnameOverride: "pinbot-exaone"

image:
  repository: 192.168.90.53/pinbot/pinbot-exaone
  tag: "1.2b"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-secret

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

nodeSelector:
  gpu: "true"

nfs:
  server: 192.168.90.51
  path: /srv/pinbot/weights

resources:
  limits:
    nvidia.com/gpu: 1

shm:
  sizeLimit: 8Gi

env:
  - name: ENV
    value: dev

# 핵심 (vLLM 제어)
vllm:
  model: /weights/EXAONE-4.0-1.2B
  servedModelName: pinbot

  gpuMemoryUtilization: 0.4
  maxModelLen: 2048
  maxNumSeqs: 1
  tensorParallelSize: 1

  dtype: float16

ingress:
  enabled: false
